### ISSUE TITLE
Adjust credit rewards based on number of players

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#130]
By default kills award 150 credits.  This doesn't seem to work with smaller amounts of players as it takes too long to be able to find a weapon you can actually play with, especially if the other side randomly gets a low cost weapon that can be used effectively.  To solve this I propose that credit rewards are increased/decreased based on the number of players. 

For example, if the config sets 150 as the default value for credits:
- Tiny number of players get a 250% increase.  eg: 1 v 1 = 375 credits per kill.
- Small number of players get a 200% increase.  eg: 2 v 2 = 300 credits per kill.
- Medium number of players have no increase (100%).  eg: 6 v 6 = 150 credits per kill.
- High number of players get a 75% penalty.  eg: 12 v 12 = 112 credits per kill.
- Huge number of players get a 50% penalty. eg:  40 v 40 = 75 credits per kill

Have this handled by the server.cfg so that the server admin can adjust the MAX_CREDIT_ADJUST_PERCENTAGE and the MIN_CREDIT_ADJUST_PERCENTAGE in the cfg or by using a cvar, in addition to the already present default amount that can be set.

These types of adjustments should also apply to assists and bounties.

**Comment by Silverfang22** [comment]
This will also most likely need to adjust assist credits (assists may need a rework in general as they can nearly double the credit gain for a "team" if a player deals 99% of the damage and someone last hits)

Not sure about other credit sources (destroying mines, etc.)

Bounties may also need to be adjusted accordingly as it would be easier to gain a bounty (but also easier to lose it? not sure.)

**Comment by Silverfang22** [comment]
I'm wondering if we should make it so that the server tracks total amount of credits earned by each team, then gives something like 20% of the total earned credits to each player (OVER A FAIRLY LONG PERIOD OF TIME) on the team who hasn't yet earned it (a player joining late will still gain 20% of the total credits earned over time).

This keeps track of how many credits a player has earned as well, if they've earned something like 40% of the total earned credits by the team they won't gain any credits this way.

That way a player who is gaining a lot of kills quickly won't gain any extra credits, but their teammates who might not be getting many kills or lots of assist credits still have a source of income.


POSSIBLY even make the total number tracked by both teams, as a catch-up mechanic if one team is really far behind. Will probably need a lot of fine tuning.

**Comment by DarthFutuza** [comment]
Just making a note here we talked about a large amount of solutions in the discord channel to the economy problem of what happens when:
a) New players join mid match and are poor compared to everyone else
b) One team starts snowballing the other and has vastly superior equipment
c) Keeping the game competitive and fair for longer periods of time (eventually someone should win though)

There are obviously a lot of things we need to consider first before making any large changes to things like this.  Some ideas suggested:

- Rewarding temporary weapons from looted corpses
- Rewarding ammo caches from looted corpses
- Some sort of Welfare for new players to the match (eg: anyone below 50% total wealth gets +50 extra credits upon kill, anyone below 25% gets an additional )
- Fences you can sell temporary items too (located in unsafe spots
- Reward players more for killing higher value targets (eg: Give bigger bounties, reward the whole team for taking down wealthy enemy players)
-Encourage smarter playing (reward advanced tactics such as scouting, using group tactics, etc. in some ways)
-Allow players to donate extra credits to team members

**Comment by DarthFutuza** [comment]
While this is not entirely addressed, the underdog bonus and passive credit rewards have largely addressed the initial concern.  While I would still like to implement some other options such as a functional player trading system, and rewarding smart plays (tactics etc), it is unnecessary.
