### ISSUE TITLE
Missing/Broken Assets v1.3

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#240]
There were a few of these, so I'm just going to put them all in one report:
- [ ] - Westar done?
- [ ] - L8 Striker needs texturing work and LODs
- [ ] - E33 needs LODs
- [ ] - Concussion rifle beam firemode is missing a texture, we had it at one point so the asset just needs the missing pieces most likely.
- [x] - Poison Grenades were not initially included in the first (also a new model would be nice, but not necessary).
- [x] - Some missing shield charge/recharge sounds should be added (I made several of these, but need to adjust the shield itm files to make them work).  This should help fix #233 
- [x] - E33 included?
- [x] - GLUA / Server Side not included in Asset5.pk3

Feel free to add others if I've missed stuff.

**Comment by eezstreet** [comment]
the EE-3 is included, it's just missing textures

**Comment by eezstreet** [comment]
Can you link your sound effects and poison grenade model stuff?

**Comment by Pande** [comment]
I think I have textures for the  ee 3 somewhere let me take a peek

On Dec 12, 2017 6:56 PM, "Nick" <notifications@github.com> wrote:

Can you link your sound effects and poison grenade model stuff?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JKGDevs/JediKnightGalaxies/issues/240#issuecomment-351234918>,
or mute the thread

**Comment by Silverfang22** [comment]
Textures aren't missing, shader was broken

**Comment by DarthFutuza** [comment]
Shield itms have been adjusted, sending new sounds to eezstreet

**Comment by eezstreet** [comment]
The majority of these aren't going to get done by the v1.3 playtest, like the L-8 Striker textures. I'm going to close this and we can do each separate one piecemeal.
