### ISSUE TITLE
Auto Equip equipment

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#289]
Auto equip items such as shields and jetpacks. If one is already equipped swap it for the new one automatically (possibly cvar this so players can turn off autoequipping behavior, possibly altogether as well as just swapping shield/jetpack behavior).

Discussion topic: Should these items that aren't usable from the ACI go to the last slot available as opposed to the first?

**Comment by DarthFutuza** [comment]
I'm going to set it so that jetpacks and shields will autoequip if its the first time you are buying one, but will not swap out if you already have one equipped - you will manually need to do this.  They will equip to 0 first if the slot is not already in use.  I'm also going to try and get the aci auto assign for weapons, etc to try to use 1 before they use 0 or other aci slots.

What other items might possibly need auto equip behavior.  Bacta?  Other consumables?

**Comment by Silverfang22** [comment]
Funny enough I think consumables like bacta might already auto-equip

**Comment by DarthFutuza** [comment]
Partially fixed in f63218 I'm not going to address the 'use of slot 1 first, and then other slots with slot 0 being last' due to the way its been setup its more work than its worth imo.  For now they'll just autoequip as long as you don't already have a shield or jetpack equipped.  Consumables will now also autoequip if you don't already have an existing stack equipped.
