### ISSUE TITLE
Can fire weapons/throw grenades through thin walls + players

### ISSUE THREAD

**Issue by xycaleth** [JKGDevs/JediKnightGalaxies#95]
It's possible to throw grenades or fire weapons through thin walls. This was discovered on the ctf bespin map with the broken doors. Stand as close as you can to the door and fire or throw.

Works on players too, if you are as close to them as possible.

**Comment by Silverfang22** [comment]
Currently guns appear to make lasers come out of your face

Make a default position when firing from the hip
Make a default position when firing from aiming down sights
Allow custom positions to be defined per weapon in .wpn file

Needs to be separate because if you are aiming down sights you shouldn't hit a wall to your right.

**Comment by eezstreet** [comment]
No longer seems to occur (see: #186). Reopening the old issue though because that one still needs fixed (although more for low priority, visual reasons that can be delayed)
